--This is autogenerated by colorwalkeditor.

local ColorWalkP2 = { background, foreground, objects = {}, objectCount, nextLevel};
ColorWalkP2.background = "images/ColorWalk-P2.png";
ColorWalkP2.foreground = "null";
ColorWalkP2.objectCount = 1;
ColorWalkP2.nextLevel = "";
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
ColorWalkP2.objects[1] = {};
ColorWalkP2.objects[1].ID          = 0;
ColorWalkP2.objects[1].imagePath   = "images/ColorWalkSprite.png";
ColorWalkP2.objects[1].soundPath   = "sound/";
ColorWalkP2.objects[1].touchableId = "brownDog";
ColorWalkP2.objects[1].imageName   = "ColorWalkSprite.png";
ColorWalkP2.objects[1].soundName   = "";
ColorWalkP2.objects[1].imageX      = 16;
ColorWalkP2.objects[1].imageY      = 666;
ColorWalkP2.objects[1].width       = 157;
ColorWalkP2.objects[1].height      = 179;
ColorWalkP2.objects[1].screenY     = 753;
ColorWalkP2.objects[1].screenX     = 891;
ColorWalkP2.objects[1].isFinal     = true;
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
return ColorWalkP2;
