--This is autogenerated by colorwalkeditor.

local first = { background, foreground, objects = {}, objectCount, nextLevel};
first.background = "images/roomOne.png";
first.foreground = "null";
first.objectCount = 2;
first.nextLevel = second;
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
first.objects[1] = {};
first.objects[1].ID          = 0;
first.objects[1].imagePath   = "images/touchables.png";
first.objects[1].soundPath   = "sound/Cardinal-bird-call.mp3";
first.objects[1].touchableId = "p1 red bird";
first.objects[1].imageName   = "touchables.png";
first.objects[1].soundName   = "Cardinal-bird-call.mp3";
first.objects[1].imageX      = 481;
first.objects[1].imageY      = 44;
first.objects[1].width       = 77;
first.objects[1].height      = 61;
first.objects[1].scaleX      = 1.0;
first.objects[1].scaleY      = 1.0;
first.objects[1].screenY     = 311;
first.objects[1].screenX     = 866;
first.objects[1].rotation    = 0.0;
first.objects[1].isFinal     = "no";
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
first.objects[2] = {};
first.objects[2].ID          = 1;
first.objects[2].imagePath   = "images/touchables.png";
first.objects[2].soundPath   = "sound/none";
first.objects[2].touchableId = "p1 green helicopter";
first.objects[2].imageName   = "touchables.png";
first.objects[2].soundName   = "none";
first.objects[2].imageX      = 333;
first.objects[2].imageY      = 42;
first.objects[2].width       = 138;
first.objects[2].height      = 68;
first.objects[2].scaleX      = 1.0;
first.objects[2].scaleY      = 1.0;
first.objects[2].screenY     = 1172;
first.objects[2].screenX     = 832;
first.objects[2].rotation    = 35.0;
first.objects[2].isFinal     = "no";
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
return first;
