--This is autogenerated by colorwalkeditor.

local ColorWalkP1 = { background, foreground, objects = {}, objectCount, nextLevel};
ColorWalkP1.background = "images/ColorWalk-P1.png";
ColorWalkP1.foreground = "null";
ColorWalkP1.objectCount = 1;
ColorWalkP1.nextLevel = "ColorWalkP2";
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
ColorWalkP1.objects[1] = {};
ColorWalkP1.objects[1].ID          = 0;
ColorWalkP1.objects[1].imagePath   = "images/ColorWalkSprite.png";
ColorWalkP1.objects[1].soundPath   = "sound/";
ColorWalkP1.objects[1].touchableId = "redCar";
ColorWalkP1.objects[1].imageName   = "ColorWalkSprite.png";
ColorWalkP1.objects[1].soundName   = "";
ColorWalkP1.objects[1].imageX      = 83;
ColorWalkP1.objects[1].imageY      = 11;
ColorWalkP1.objects[1].width       = 74;
ColorWalkP1.objects[1].height      = 38;
ColorWalkP1.objects[1].screenY     = 943;
ColorWalkP1.objects[1].screenX     = 922;
ColorWalkP1.objects[1].isFinal     = true;
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
return ColorWalkP1;
