--This is autogenerated by colorwalkeditor.

local ColorWalkP2 = { background, foreground, objects = {}, objectCount, nextLevel};
ColorWalkP2.background = "images/ColorWalk-P2.png";
ColorWalkP2.foreground = "null";
ColorWalkP2.objectCount = 1;
ColorWalkP2.nextLevel = "";
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
ColorWalkP2.objects[1] = {};
ColorWalkP2.objects[1].ID          = 0;
ColorWalkP2.objects[1].imagePath   = "images/ColorWalkSprite.png";
ColorWalkP2.objects[1].soundPath   = "sound/";
ColorWalkP2.objects[1].touchableId = "brownDog";
ColorWalkP2.objects[1].imageName   = "ColorWalkSprite.png";
ColorWalkP2.objects[1].soundName   = "";
ColorWalkP2.objects[1].imageX      = 16;
ColorWalkP2.objects[1].imageY      = 666;
ColorWalkP2.objects[1].width       = 157;
ColorWalkP2.objects[1].height      = 179;
ColorWalkP2.objects[1].screenY     = 753;
ColorWalkP2.objects[1].screenX     = 891;
ColorWalkP2.objects[1].isFinal     = true;
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
local composer = require( "composer" )
local touchable = require("src.Touchable")
 
local scene = composer.newScene()
 
-- ----------------------------------------------------------------------------------- 
-- Code outside of the scene event functions below will only be executed ONCE unless   
-- the scene is removed entirely (not recycled) via "composer.removeScene()"           
-- ----------------------------------------------------------------------------------- 
                                                                                       
local nextLevelName = "mainMenu"                                                     
                                                                                       
 local function nextLevel(event)                                                       
    if(event.phase == "ended") then                                                  
        local options = {                                                              
                            effect = "slideLeft",                                     
                            time = 800,                                                 
                            params = {levelName = nextLevelName}                        
                        }                                                               
        print(nextLevelName)                                                            
        if(nextLevelName ~= "mainMenu") then                                            
            composer.gotoScene("pages." .. "nextLevelName", options)                                  
        else                                                                            
            composer.gotoScene("mainMenu", options)                                     
        end                                                                             
    end                                                                                 
 end                                                                                    
                                                                                        
-- -----------------------------------------------------------------------------------  
-- Scene event functions                                                                
-- -----------------------------------------------------------------------------------  
                                                                                        
                                                                                        
-- create()                                                                             
function scene:create( event )                                                          
                                                                                        
    local sceneGroup = self.view                                                        
    -- Code here runs when the scene is first created but has not yet appeared on screen

end
 
 
-- show()
function scene:show( event )                            
                                                        
                                                        
    local sceneGroup = self.view                        
    local phase = event.phase                           
    local backgroundImage;                              
    local foregroundImage;                              
    local objects  = {};                                
                                                        
    if ( phase == "will" ) then                       
        -- Code here runs when the scene is still off screen (but is about to come on screen)
    if(ColorWalkP2.nextLevel ~= "" and ColorWalkP2.nextLevel ~= "mainMenu") then                           
        nextLevelName = ColorWalkP2.nextLevel;                                                      
    else                                                                                     
        nextLevelName = "mainMenu"                                                           
    end                                                                                      
    if ColorWalkP2.background ~= "none" and ColorWalkP2.background ~= "null" then                          
        backgroundImage = display.newImageRect(ColorWalkP2.background, display.actualContentWidth, display.actualContentHeight);
        backgroundImage.x = display.contentCenterX                                                                       
        backgroundImage.y = display.contentCenterY                                                                       
        sceneGroup:insert(backgroundImage)                                                                               
    end                                                                                                                  
    if(ColorWalkP2.foreground ~= "none" and ColorWalkP2.foreground ~= "null") then                                                     
        foregroundImage = display.newImageRect(ColorWalkP2.foreground, display.actualContentwidth, display.actualContentHeight);
        foregroundImage.x = display.contentCenterX                                                                       
        foregroundImage.y = display.contentCenterY                                                                       
        sceneGroup:insert(foregroundImage)                                                                               
    end                                                                                                                  
    local temp = ColorWalkP2.objects[1];                                                                                        
    print(temp.ID);                                                                                                      
    print(temp.soundPath)                                                                                                
    --touchable:createTouchable(temp);                                                                                   
                                                                                                                         
    --objects[1] = touchable:createTouchable(ColorWalkP2.objects[1]);                                                           
    local temp = {};                                                                                                     
    for i = 1, ColorWalkP2.objectCount do --pseudocode                                                                          
        objects[i] = touchable:createTouchable(ColorWalkP2.objects[i]);                                                         
                                                                                                                         
        if ColorWalkP2.objects[i].isFinal == true then                                                                          
            objects[i]:addEventListener("touch", nextLevel)                                                              
        end                                                                                                              
        sceneGroup:insert(objects[i])                                                                                    
    end                                                                                                                  
    elseif ( phase == "did" ) then                                                                                       
        -- Code here runs when the scene is entirely on screen                                                           
                                                                                                                         
    end                                                                                                                  
                                                                                                                         
end                                                                                                                      
                                                                                                                         
                                                                                                                         
-- hide()                                                                                                                
function scene:hide( event )                                                                                             
                                                                                                                         
    local sceneGroup = self.view                                                                                         
    local phase = event.phase                                                                                            
                                                                                                                         
    if ( phase == "will" ) then                                                                                          
        -- Code here runs when the scene is on screen (but is about to go off screen)                                    
                                                                                                                         
    elseif ( phase == "did" ) then                                                                                       
        -- Code here runs immediately after the scene goes entirely off screen                                           
                                                                                                                         
    end                                                                                                                  
end                                                                                                                      
                                                                                                                         
                                                                                                                         
-- destroy()                                                                                                             
function scene:destroy( event )                                                                                          
                                                                                                                         
    local sceneGroup = self.view                                                                                         
    -- Code here runs prior to the removal of scene's view                                                               
                                                                                                                         
end                                                                                                                      
                                                                                                                         
                                                                                                                         
-- -----------------------------------------------------------------------------------                                   
-- Scene event function listeners                                                                                        
-- -----------------------------------------------------------------------------------                                   
scene:addEventListener( "create", scene )                                                                                
scene:addEventListener( "show", scene )                                                                                  
scene:addEventListener( "hide", scene )                                                                                  
scene:addEventListener( "destroy", scene )                                                                               
-- -----------------------------------------------------------------------------------                                   
               
return scene   
