--This is autogenerated by colorwalkeditor.

local ColorWalkP1 = { background, foreground, objects = {}, objectCount, nextLevel};
ColorWalkP1.background = "images/ColorWalk-P1.png";
ColorWalkP1.foreground = "null";
ColorWalkP1.objectCount = 1;
ColorWalkP1.nextLevel = "ColorWalkP2";
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
ColorWalkP1.objects[1] = {};
ColorWalkP1.objects[1].ID          = 0;
ColorWalkP1.objects[1].imagePath   = "images/ColorWalkSprite.png";
ColorWalkP1.objects[1].soundPath   = "sound/";
ColorWalkP1.objects[1].touchableId = "redCar";
ColorWalkP1.objects[1].imageName   = "ColorWalkSprite.png";
ColorWalkP1.objects[1].soundName   = "";
ColorWalkP1.objects[1].imageX      = 83;
ColorWalkP1.objects[1].imageY      = 11;
ColorWalkP1.objects[1].width       = 74;
ColorWalkP1.objects[1].height      = 38;
ColorWalkP1.objects[1].screenY     = 921;
ColorWalkP1.objects[1].screenX     = 968;
ColorWalkP1.objects[1].isFinal     = true;
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
local composer = require( "composer" )
local touchable = require("src.Touchable")
 
local scene = composer.newScene()
 
-- ----------------------------------------------------------------------------------- 
-- Code outside of the scene event functions below will only be executed ONCE unless   
-- the scene is removed entirely (not recycled) via "composer.removeScene()"         
-- ----------------------------------------------------------------------------------- 
                                                                                       
local nextLevelName = "mainMenu"                                                     
                                                                                       
 local function nextLevel(event)                                                       
    if(event.phase == "ended") then                                                  
        local options = {                                                              
                            effect = "slideLeft",                                    
                            time = 800,                                                
                            params = {levelName = nextLevelName}                       
                        }                                                              
        print(nextLevelName)                                                           
        if(nextLevelName ~= "mainMenu") then                                          
            composer.gotoScene("pages." .. nextLevelName, options)                    
        else                                                                            
            composer.gotoScene("mainMenu", options)                                   
        end                                                                             
    end                                                                                 
 end                                                                                    
                                                                                        
-- -----------------------------------------------------------------------------------  
-- Scene event functions                                                                
-- -----------------------------------------------------------------------------------  
                                                                                        
                                                                                        
-- create()                                                                             
function scene:create( event )                                                          
                                                                                        
    local sceneGroup = self.view                                                        
    -- Code here runs when the scene is first created but has not yet appeared on screen

end
 
 
-- show()
function scene:show( event )                            
                                                        
                                                        
    local sceneGroup = self.view                        
    local phase = event.phase                           
    local backgroundImage;                              
    local foregroundImage;                              
    local objects  = {};                                
                                                        
    if ( phase == "will" ) then                       
        -- Code here runs when the scene is still off screen (but is about to come on screen)
    if(ColorWalkP1.nextLevel ~= "" and ColorWalkP1.nextLevel ~= "mainMenu") then                           
        nextLevelName = ColorWalkP1.nextLevel;                                                      
    else                                                                                     
        nextLevelName = "mainMenu"                                                           
    end                                                                                      
    if ColorWalkP1.background ~= "none" and ColorWalkP1.background ~= "null" then                          
        backgroundImage = display.newImageRect(ColorWalkP1.background, display.actualContentWidth, display.actualContentHeight);
        backgroundImage.x = display.contentCenterX                                                                       
        backgroundImage.y = display.contentCenterY                                                                       
        sceneGroup:insert(backgroundImage)                                                                               
    end                                                                                                                  
    if(ColorWalkP1.foreground ~= "none" and ColorWalkP1.foreground ~= "null") then               
        foregroundImage = display.newImageRect(ColorWalkP1.foreground, display.actualContentwidth, display.actualContentHeight);
        foregroundImage.x = display.contentCenterX                                                                       
        foregroundImage.y = display.contentCenterY                                                                       
        sceneGroup:insert(foregroundImage)                                                                               
    end                                                                                                                  
    local temp = ColorWalkP1.objects[1];                                                                       
    print(temp.ID);                                                                                                      
    print(temp.soundPath)                                                                                                
    --touchable:createTouchable(temp);                                                                                   
                                                                                                                         
    --objects[1] = touchable:createTouchable(ColorWalkP1.objects[1]);                                          
    local temp = {};                                                                                                     
    for i = 1, ColorWalkP1.objectCount do --pseudocode                                                         
        objects[i] = touchable:createTouchable(ColorWalkP1.objects[i]);                                        
                                                                                                                         
        if ColorWalkP1.objects[i].isFinal == true then                                                         
            objects[i]:addEventListener("touch", nextLevel)
        else
            objects[i]:addEventListener("touch", objects[i].onEvent())
        end                                                                                                              
        sceneGroup:insert(objects[i])                                                                                    
    end                                                                                                                  
    elseif ( phase == "did" ) then                                                                                     
        -- Code here runs when the scene is entirely on screen                                                           
                                                                                                                         
    end                                                                                                                  
                                                                                                                         
end                                                                                                                      
                                                                                                                         
                                                                                                                         
-- hide()                                                                                                                
function scene:hide( event )                                                                                             
                                                                                                                         
    local sceneGroup = self.view                                                                                         
    local phase = event.phase                                                                                            
                                                                                                                         
    if ( phase == "will" ) then                                                                                        
        -- Code here runs when the scene is on screen (but is about to go off screen)                                    
                                                                                                                         
    elseif ( phase == "did" ) then                                                                                     
        -- Code here runs immediately after the scene goes entirely off screen                                           
                                                                                                                         
    end                                                                                                                  
end                                                                                                                      
                                                                                                                         
                                                                                                                         
-- destroy()                                                                                                             
function scene:destroy( event )                                                                                          
                                                                                                                         
    local sceneGroup = self.view                                                                                         
    -- Code here runs prior to the removal of scene's view                                                               
                                                                                                                         
end                                                                                                                      
                                                                                                                         
                                                                                                                         
-- -----------------------------------------------------------------------------------                                   
-- Scene event function listeners                                                                                        
-- -----------------------------------------------------------------------------------                                   
scene:addEventListener( "create", scene )                                                                              
scene:addEventListener( "show", scene )                                                                                
scene:addEventListener( "hide", scene )                                                                                
scene:addEventListener( "destroy", scene )                                                                             
-- -----------------------------------------------------------------------------------                                   
               
return scene   
